### ISSUE TITLE
[version 2.3.1] EXT-X-MEDIA parser support.

### ISSUE THREAD

**Issue by pfdtk** [chrisyue/php-m3u8#39]
I know that tag `EXT-X-MEDIA` is not ready in version 2.3.1, but i want to get it done  by myself. 
But where is the best place shoud I put my code in the `php-m3u8` library? 
- Place in `M3u8::__construct()` and where?
- Place in `Segment::__construct()` and where?

**Comment by chrisyue** [comment]
As the `#EXT-X-MEDIA` tag is [defined](https://tools.ietf.org/html/rfc8216#page-25) under "Master Playlist" section in RFC8216, it should be placed in `M3u8` (`M3u8` is considered as a "playlist")

**Comment by pfdtk** [comment]
Thanks for your answer @chrisyue, do you has any plan to add the missing tags?

**Comment by chrisyue** [comment]
@pfdtk yes, but it's for 3.0 version, as adding new tag support is really simple in 3.0

**Comment by pfdtk** [comment]
Awesome, can`t wait to use it.

**Comment by chrisyue** [comment]
3.0 is released
