### ISSUE TITLE
希望可以支援双语（多语）结构的 M3U8 格式

### ISSUE THREAD

**Issue by Caringor** [chrisyue/php-m3u8#49]
您好，最近有个 HLS 反代的需求需要用到您的库，使用中发现索引中的多条（音、字幕）轨只能被识别到最后一条。

![image](https://user-images.githubusercontent.com/11784575/53949025-23ee3880-4104-11e9-9e18-20e82cb50c3b.png)
(原始 M3U8 索引文件)

![image](https://user-images.githubusercontent.com/11784575/53949344-ce665b80-4104-11e9-8dbf-4247bedbdfc8.png)
(Parse 后的数组，只匹配了最后一个 EXT-X-MEDIA 数据)

**Comment by chrisyue** [comment]
3.2.3 已经修复此问题。

怪我读文档不仔细，感谢 

相关 PR #50
