### ISSUE TITLE
兼容解析 media playlist 标签写在 media segment 标签之后的非标准 M3u8 内容

### ISSUE THREAD

**Issue by Caringor** [chrisyue/php-m3u8#51]
大大您好，我又来提 BUG 了…

这次发现的问题是 DumperFacade 组件在利用 dump() 方法生成播放列表的时候，会把原列表上的 EXT-X-MEDIA-SEQUENCE 字段无视掉，这个参数对于直播来说非常重要。如果该字段丢失，会令播放器出现断流的问题。

![image](https://user-images.githubusercontent.com/11784575/54067846-25dd0680-4280-11e9-80e6-6a9b18dd7186.png)
(原始播放列表)

![image](https://user-images.githubusercontent.com/11784575/54067828-faf2b280-427f-11e9-878d-8fccd2219879.png)
(经过 Parse 后再重新生成的播放列表，可以看到 EXT-X-MEDIA-SEQUENCE 字段被舍弃了)

**Comment by Caringor** [comment]
刚刚发现好像只要把 tags.php 内 EXT-X-MEDIA-SEQUENCE 字段下的 category 的值改成 media-segment 就可以了，就是不知道会不会有什么副作用

![image](https://user-images.githubusercontent.com/11784575/54069441-056a7780-4293-11e9-948d-2b85e5e07c65.png)

**Comment by chrisyue** [comment]
@Caringor hi, 小伙伴，你把你 dump 出问题的 m3u8 发出来发给我，我本地用另外的 m3u8 无法复现 dump 没有 EXT-X-MEDIA-SEQUENCE 的问题

**Comment by chrisyue** [comment]
在看了你的截图之后，我猜测是因为原 M3U8 把 EXT-X-KEY 写在了 EXT-X-MEDIA-SEQUENCE 之前的原因。

当 PHP M3U8 在处理 media segment 标签的时候（比如 EXT-X-KEY），就认为已经进入了解析 media segment 的阶段，而 EXT-X-MEDIA-SEQUENCE 属于 media playlist 标签，就不解析了。所以应该还不是 dump 出问题，在 parse 的时候其实就抛弃了。

解决方案：

1. 如果原输出 M3U8 内容是你可以控制的，把 EXT-X-KEY 和 EXT-X-MEDIA-SEQUENCE 的顺序换一下就行了
2. 如果原输出你控制不了，你现在的做法也可以，只是比较 hack，其实就是把 EXT-X-MEDIA-SQUENCE 定义为了 media segment 标签而已，那么导致的问题你也应该猜得到，media segment 标签都是可以出现多次的，EXT-X-MEDIA-SQUENCE 也变成被定义成可以出现多次，dump 出来也就会出现多次。只不过如果你只是 parse 完就 dump，那没有大碍，毕竟原 M3u8 文件本来就只有一个 EXT-X-MEDIA-SEQUENCE

**Comment by chrisyue** [comment]
这个 issue 我先留着，有时间我需要看看 RFC 里有没有说 media playlist 标签不能放在 media segment 标签之后，如果允许的话，那这个问题的确算 bug

**Comment by Caringor** [comment]
您好，尝试了下把 SEQUENCE 标签的位置上移，的确能解决问题，但是好像目前很多平台的节目源（使用 Wowza Media Server 作为流媒体服务端）都喜欢把 EXT-X-MEDIA-SEQUENCE 标签标记在所有 EXT-X-* 的标签的最下面，位置互换的话操作上会不太方便。
附上 [播放列表 Example](https://gist.github.com/Caringor/94d2f7c9c49c65f557e817133e642980)

**Comment by Caringor** [comment]
> 这个 issue 我先留着，有时间我需要看看 RFC 里有没有说 media playlist 标签不能放在 media segment 标签之后，如果允许的话，那这个问题的确算 bug

十分感谢大大的回复，那我目前暂时就把 category 字段替换成 media-segment 来用着吧。

**Comment by chrisyue** [comment]
RFC8216 有要求 [EXT-X-MEDIA-SEQUENCE 必须写在第一个 media segment 之前](https://tools.ietf.org/html/rfc8216#section-4.3.3.2)

> The EXT-X-MEDIA-SEQUENCE tag MUST appear before the first Media
> Segment in the Playlist.

不过我认为这只是纯规范的问题，顺序并不影响 M3u8 文件的完整性，所以还是应该兼容这种写法
