### ISSUE TITLE
现在的设计，解析之后没有办法对元素标签进行属性修改，只能dump的时候做各种拼装

### ISSUE THREAD

**Issue by ihipop** [chrisyue/php-m3u8#58]
解析以后，所有的mediaSegments内的元素属性都是只读的，比如**Inf**标签，我想遍历这些元素，找出Inf标签的CCTV-1的TITLE，然后把uri进行修改和替换，貌似做不到。为什么这么设计呢?
如果parse后只能用自定义 dump函数的方法控制输出，我直接按行文本查找都比较快。
我现在自定义了我的**Inf**标签类，把这些属性都改成可读写了，毕竟我读取列表不是为了只是解析一下然后就dump成文本的。

**Comment by chrisyue** [comment]
其实没有什么原因哈，主要看需求。
你有这个需求，我可以改成可读写的没有问题

**Comment by ihipop** [comment]
我的意思是，这样的设计让这个库开箱即用性大大减少，基本上我需要修改的标签每个都得重新定义一遍。

**Comment by chrisyue** [comment]
> 我的意思是，这样的设计让这个库开箱即用性大大减少，基本上我需要修改的标签每个都得重新定义一遍。

对于你的需求来说是这样，这个库的初衷就只是为了纯粹的导出或者解析方便而已

**Comment by chrisyue** [comment]
@ihipop 抱歉最近忙别的去了。你看看 PR #60 满足你的需求否，OK 我就合并了。

**Comment by ihipop** [comment]
@chrisyue 其实我说的是多方面的，比如说，修改、构建EXT-X-KEY的加密方式属性和URI
现在有从对象方式构建、修改M3U标签的全部开放接口吗？

**Comment by chrisyue** [comment]
> @chrisyue 其实我说的是多方面的，比如说，修改、构建EXT-X-KEY的加密方式属性和URI
> 现在有从对象方式构建、修改M3U标签的全部开放接口吗？

现在应该就可以吧，自带的标签处理除了 EXTINF 全都是 AccessObject，理论上直接改就行了。

关于之前你说的Media segment 的 uri 的问题，Media segment 本身也是 AccessObject，它的 uri 也是直接改就行了，这个我在本地测过，是可以的
