### ISSUE TITLE
我想了半天 他确实没有这个

### ISSUE THREAD

**Issue by puzzle9** [chrisyue/php-m3u8#63]
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-MEDIA-SEQUENCE:1614843567
#EXT-X-TARGETDURATION:4
#EXTINF:3.008,
emhFT1paQjRkU291XzE=_orig-1614843567.ts
#EXTINF:3.008,
emhFT1paQjRkU291XzE=_orig-1614843568.ts
#EXTINF:3.008,
emhFT1paQjRkU291XzE=_orig-1614843569.ts
```

就是 获取 `hls` 时候 取一个绝对路径

**Comment by chrisyue** [comment]
你这标题能不能好好写，我还以为是什么垃圾或者广告啥的……

感觉你说的绝对路径功能，做在库里的价值不大啊

**Comment by puzzle9** [comment]
当时用的是 https://github.com/globocom/m3u8 这个扩展
然后 他是一套集成了
然后 就到php这里来了 
好像 就是获取ts文件时候方便点 再也没其他作用了



<blockquote><img src="https://avatars.githubusercontent.com/u/83798?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/globocom/m3u8">globocom/m3u8</a></strong></div><div>Python m3u8 Parser for HTTP Live Streaming (HLS) Transmissions - globocom/m3u8</div></blockquote>

**Comment by chrisyue** [comment]
我倾向于每个库责任少而精，把解析 m3u8 格式本身这个事情做好就行了
