### ISSUE TITLE
When parsing the manifest file, I get the Exception "$ offset should be an integer greater than 0".

### ISSUE THREAD

**Issue by KazukiSugiyama107** [chrisyue/php-m3u8#67]
When I wrote the code according to the implementation example of READEME, the following Exception occurred.
```
[App\Exceptions\Handler] InvalidArgumentException: $offset should be an integer greater than 0 in /var/www/mgsplayer_api/vendor/chrisyue/php-m3u8/src/Data/Value/Tag/Byterange.php:33
```

The master manifest can be parsed without any problems, but only the media manifest has an Exception.
Do you know what caused it?

The following is a partial excerpt of the contents of the manifest file that is about to be parsed.
```
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-TARGETDURATION:7
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="***"
#EXTINF:6.006,
#EXT-X-BYTERANGE:300800@0
***_6000.ts
#EXTINF:6.006,
#EXT-X-BYTERANGE:335204@300800
***_6000.ts
```

* version : "chrisyue/php-m3u8": "^3"

**Comment by KazukiSugiyama107** [comment]
This was due to the implementation method.
Closed because it has been resolved.

**Comment by tauri77** [comment]
Why don't you allow a zero offset range?
I can't find anything in the EXT-X-BYTERANGE section of rfc8216 that refers to this limit.

I came across this apple example:
https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8
->
https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/v5/prog_index.m3u8
Which has:

> #EXT-X-MAP:URI="main.mp4",BYTERANGE="719@**0**"

And it gives an error in the Byterange class where:
```
if ($this->offset < 1) {
   throw new \InvalidArgumentException('$offset should be an integer greater than 0');
}
```

<blockquote></blockquote>

**Comment by chrisyue** [comment]
> Why don't you allow a zero offset range? I can't find anything in the EXT-X-BYTERANGE section of rfc8216 that refers to this limit.
> 
> I came across this apple example: https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8 -> https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/v5/prog_index.m3u8 Which has:
> 
> > #EXT-X-MAP:URI="main.mp4",BYTERANGE="719@**0**"
> 
> And it gives an error in the Byterange class where:
> 
> ```
> if ($this->offset < 1) {
>    throw new \InvalidArgumentException('$offset should be an integer greater than 0');
> }
> ```

you are right about the limitation, it'll be fixed in the next release
